name: GitHub Actions Demo

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Git Hub Actions"
      - run: ls -lt
      - run: pwd
      - run: echo "branch name ${{ github.ref }}"
      - run: echo "trigger ${{ github.event_name }}"
      - run: echo "runner.os ${{ runner.os }}"
      - run: echo "repo name ${{ github.repository}}"
      - run: echo ""
      - name: check out repo
        uses: actions/checkout@v5
      - run: ls -lt
      - run: python hello.py




